version: "3.8"
services:

  consumer:
    build:
      context: redis-stream-consumer
    environment:
      - SPRING_REDIS_HOST=redis

  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db

volumes:
  redis_data:
  redisinsight_data: